"""Script to insert/delete initial/test data into the database"""
from database import Database

def populate():
    """Populates the plant collection in the database"""
    plant_data = [
        {"id": 1, "name": "assorted echeveria", "description": "Looking for a stunning succulent to add to your collection? Look no further than the Echeveria plant! With its thick, fleshy rosette-shaped leaves and vibrant colors ranging from pale green to deep purple, this plant is sure to catch your eye. Echeveria plants are easy to care for and perfect for indoor or outdoor settings. They also produce clusters of fragrant flowers in the summer and fall, making them a favorite of pollinators like bees. Don't miss out on the beauty and charm of the Echeveria plant - pick one up for your home or garden today!", "price": 6.0, "inventory": 10, "care_sunlight": "Place Echeveria plants in a spot with bright, indirect sunlight for at least six hours a day.", "care_water": "Water Echeveria plants sparingly at the base with room temperature water, allowing the soil to dry out completely between watering and draining any excess water to avoid root rot."},
        {"id": 2, "name": "snake plant", "description": "If you're looking for a low-maintenance plant that still packs a punch in the style department, look no further than the Snake Plant! With its striking upright leaves and unique variegation patterns, this plant is a great addition to any home or office space. Snake plants are known for their durability and can thrive in a variety of light conditions, making them perfect for those who don't have a lot of time to devote to plant care. Plus, they have air-purifying qualities, making them a healthy addition to your indoor environment. Don't miss out on the timeless elegance of the Snake Plant - bring one home today!", "price": 6.0, "inventory": 10, "care_sunlight": "Snake plants prefer indirect light but can tolerate low light conditions, so place them in a spot with bright to low indirect sunlight for a few hours a day.", "care_water": "Water snake plants sparingly, allowing the soil to dry out completely between watering, and avoid getting water on the leaves to prevent the plant from rotting."},
        {"id": 3, "name": "money tree", "description": "Looking for a plant that's believed to bring good luck and fortune? The Money Tree may be just what you need! With its distinctive braided trunk and lush, glossy leaves, this plant is a favorite of both Feng Shui enthusiasts and indoor plant lovers alike. Money Trees are known for their resilience and adaptability, making them a great choice for beginners. Plus, they're said to bring positive energy and abundance into the home or workplace. Whether you're looking to spruce up your décor or attract prosperity, the Money Tree is a must-have for any plant collection.", "price": 6.0, "inventory": 10, "care_sunlight": "Money trees thrive in bright, indirect sunlight, so place them in a well-lit room, away from direct sunlight or harsh, dark corners.", "care_water": "Water money trees deeply once a week, allowing the top inch of soil to dry out between watering and ensure good drainage to prevent root rot."},
        {"id": 4, "name": "golden pothos", "description": "The Pothos plant, also known as Devil's Ivy, is a popular houseplant due to its beautiful trailing vines and low-maintenance nature. With its heart-shaped leaves and variegated patterns, this plant is an attractive addition to any indoor space. Pothos plants are known for their hardiness and adaptability, thriving in low to bright light conditions and requiring only occasional watering. They're also great for purifying the air, making them a healthy choice for your home or office. Whether you're a seasoned plant lover or just starting out, the Pothos plant is an easy and beautiful choice.", "price": 6.0, "inventory": 10, "care_sunlight": "Pothos plants prefer bright, indirect sunlight, but can also tolerate low light conditions, so place them in a well-lit room away from direct sunlight or in a low to medium-light area.", "care_water": "Water pothos plants when the top inch of soil feels dry, allowing the excess water to drain out from the bottom of the pot, and avoid overwatering to prevent root rot."},
        {"id": 5, "name": "cactus", "description": "Cacti are a unique and fascinating addition to any plant collection! With their prickly spines and unusual shapes, cacti are instantly recognizable and are a great way to add a touch of the desert to your home or office. These plants are known for their hardiness and require very little watering, making them an excellent choice for those who are new to plant care or have a busy lifestyle. Cacti come in a wide variety of shapes, sizes, and colors, from tall and columnar to short and spherical, making them a versatile and interesting addition to any space. Add a cactus to your collection today and enjoy the beauty and resilience of these incredible plants!", "price": 6.0, "inventory": 10, "care_sunlight": "Cacti require plenty of bright, direct sunlight, so place them in a south or west-facing window or outside in full sun for at least 6 hours a day.", "care_water": "Water cacti thoroughly, but only when the soil has dried out completely, and ensure good drainage to avoid waterlogged soil and root rot."},
        {"id": 6, "name": "air plant", "description": "Air plants, also known as Tillandsia, are an exciting and unique addition to any plant collection! These plants are known for their ability to grow without soil, instead absorbing nutrients and moisture from the air through their leaves. Air plants come in a variety of shapes and sizes, with many featuring stunning and unusual flowers. They're easy to care for and require only occasional misting or soaking, making them a low-maintenance choice for busy plant lovers. Air plants are also incredibly versatile, able to be displayed in a variety of creative ways, from hanging baskets to terrariums. Bring the wonder of the air plant into your home or office today and enjoy the beauty and intrigue of these fascinating plants!", "price": 6.0, "inventory": 10, "care_sunlight": "Air plants require bright, indirect light or filtered sunlight, so place them near a window or in a bright, well-lit room with good air circulation.", "care_water": "Water air plants by misting them once or twice a week, or soaking them in water for 10-15 minutes once every two weeks, and allowing them to dry completely before returning them to their display."},
    ]
    for plant in plant_data:
        Database.add_product(product=plant)

def clear():
    """Clear the plant collection in the database"""
    Database.plants.delete_many({})

def display():
    """Print the contents of the plant collection"""
    for plant in Database.plants.find():
        print(plant)

Database.start_db()
clear()
populate()
display()